import { AR_One_Sans } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/store/UserContext";
import Header from "@/components/Header/header";
import "primeicons/primeicons.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const inter = AR_One_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Xperiento",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <ToastContainer />
          <Header />
          <div className="main-container">{children}</div>
        </UserProvider>
      </body>
    </html>
  );
}
