# Use the official Node.js image
FROM node:20.10.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that Next.js uses
EXPOSE 5173

# Run the development server
CMD ["npm", "run", "dev"]


#docker build -t xperiento-frontend:0.0.1 .

#docker run -d --restart=always -p 3001:3001 xperiento-frontend:0.0.1
